# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthPlanner_CTIS480Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SCLAlertView'

  # Pods for HealthPlanner_CTIS480Project

end
